### ISSUE TITLE
[RFC][RELEASE] Apache TVM 0.6.0 Release Candidate (verifying, feedback, etc.)

### ISSUE THREAD

**Issue by yzhliu** [apache/incubator-tvm#4406] opened 2019-11-23 05:34 UTC
Dear Community,

This is an RFC for verifying whether v0.6.0.rc2 is good to go. The release candidate (release note, artifact and source code) can be find [here](https://github.com/apache/incubator-tvm/releases/tag/v0.6.0.rc2)

This is **not** an official vote. Please help us verifying,

* Incubating in name
* DISCLAIMER exists
* LICENSE and NOTICE are fine
* No unexpected binary files
* Checked PGP signatures
* Checked Checksums
* Functionality works as expected.

For the vote afterwards, we propose to allow vote via github issue, which will be synced to @dev and back.  See historical community vote on this thread [dev@ thread: tvm apache community plan](https://lists.apache.org/thread.html/c34b728f01d1030146594e47e0706cd1990ed731d06e3c179b7d501a@%3Cdev.tvm.apache.org%3E) [github thread: tvm apache community plan](https://github.com/apache/incubator-tvm/issues/2973)

We do encourage people also subscribe [email list for tvm developers](https://lists.apache.org/list.html?dev@tvm.apache.org) by sending email to dev-subscribe@tvm.apache.org 

@markusweimer @sscdotopen @tqchen

**Comment by FrozenGene** [comment] 2019-11-25 05:21
one typo... [RUTNIME] -> [RUNTIME]

**Comment by yzhliu** [comment] 2019-11-25 05:25
@FrozenGene Thanks. Fixed just now. Also we fixed some license problem per IPMC's comments. RC1: https://github.com/apache/incubator-tvm/releases/tag/0.6.0.rc1

**Comment by tqchen** [comment] 2019-11-26 19:37
we just moved the main website to https://tvm.apache.org/, might be worth cherry pick https://github.com/apache/incubator-tvm/pull/4429

**Comment by yzhliu** [comment] 2019-11-26 21:00
@tqchen sounds good.

**Comment by tqchen** [comment] 2019-11-26 22:35
https://github.com/apache/incubator-tvm/pull/4431

**Comment by tqchen** [comment] 2019-11-27 00:47
There is a broken tutorial  https://github.com/apache/incubator-tvm/blob/master/vta/tutorials/frontend/deploy_vision_on_vta.py  which was caused by quantization changes that need to be fixed.

Originally the quantize pass won't produce multiply if the scale is power2, and it is a hard requirement for VTA because vta does not have multiplier. seems the change https://github.com/apache/incubator-tvm/pull/4295 allows creation of model with mul. @vinx13 would be great if you can help look into the problem.

**Comment by tqchen** [comment] 2019-11-27 01:37
Fixed by https://github.com/apache/incubator-tvm/pull/4433

**Comment by yzhliu** [comment] 2019-11-27 03:57
I have made another RC per IPMC's comments and includes the bug fix.
https://github.com/apache/incubator-tvm/releases/tag/v0.6.0.rc2

**Comment by tqchen** [comment] 2019-11-28 05:54
voting thread https://github.com/apache/incubator-tvm/issues/4443

**Closed by tqchen** 2019-11-28 05:54 UTC
Labels: status: help wanted
