### ISSUE TITLE
Optimization for subpixel layer on Tensor core

### ISSUE THREAD

**Issue by kice** [apache/incubator-tvm#4523] opened 2019-12-15 05:38 UTC
I found that Depth_to_Space layer spend too much time on changing data layout (NHWC <-> NCHW) while using tensor core. It takes up to 25% of the run time to do the transpose.

Is it possible to reduce this kind of unnecessary data manipulation, like combining reshape and/or transpose into one op. 

A sample network
```
scale = 4

conv(3, 64),
conv(64, scale**2),
subpixel(scale),
conv(64 // scale**2, 3)
```

Then it will do
```
scale = 4

nchwToNhwc(), 
conv(3, 64),
conv(64, scale**2),
nhwcToNchw(),
reshape and transpose
nchwToNhwc(), 
conv(64 // scale**2, 3)
nhwcToNchw(),
```
I think nchwToNhwc is done automatically by CUDA, maybe we could convert the whole to NHWC before using tensor core will be a better choice.

Or some features like this PR https://github.com/apache/incubator-tvm/pull/4335

**Comment by jwfromm** [comment] 2019-12-15 21:06
You're right that our current handling of depth2space (and space2depth) isn't optimal. We should probably have a dedicated relay op and topi implementation that directly rearranges values rather than stacking reshapes and transposes. I can try to take a stab at implementing this in the next few days.

**Comment by kice** [comment] 2019-12-16 10:30
I think it is okay that we use reshapes and transoises only if we could change the parameters when the data layout change. Some models, like EDSR, sandwich conv between subpixel for 4x scale, hurting the perforamce even worse.

But if the new op can support both NCHW and NHWC, it will be nice. xD

**Comment by jwfromm** [comment] 2019-12-22 18:55
See PR #4566 for my implementation of native sub pixel operators.

**Comment by jwfromm** [comment] 2019-12-28 17:15
@kice now that #4566 is merged, can you give this another try? Hopefully we have much better performance and this issue can be closed.

**Comment by kice** [comment] 2019-12-29 16:46
After testing it, I am happy to let you know, we have no significant difference at all. And I even found a bug. xD

**Comment by kice** [comment] 2019-12-29 17:01
<img width="959" alt="tranpose" src="https://user-images.githubusercontent.com/3945950/71559964-0ba02f00-2a32-11ea-9e22-ddd88d6693d8.png">
<img width="959" alt="native" src="https://user-images.githubusercontent.com/3945950/71559965-0ba02f00-2a32-11ea-80a3-0b0952db9847.png">

Without profiling, native finished in 55.235s, transpose finished in 55.639s. 
Warmup 200 runs with cpu copy back, and benchmark without copyback for 600 runs.

**Comment by jwfromm** [comment] 2019-12-29 21:28
Maybe the problem is just that this op shouldnt be fused when running on tensor cores. I suspect the access pattern just fundamentally causes bad behavior in the kernel. Can you try changing its fusion pattern to `OPAQUE` rather than `INJECTIVE` (~ line 976 in `tvm/relay/op/nn/_nn.py`)? Also what bug did you find? I can't see anything obvious in what you posted.

**Comment by kice** [comment] 2019-12-29 23:13
https://github.com/apache/incubator-tvm/blob/fadea9229c078f30469879ac6ab69920a2c0cbe0/python/tvm/relay/frontend/onnx.py#L542

We should decode it to str.

I think we should add more testcases for importing models.

**Comment by kice** [comment] 2019-12-29 23:41
I cannot see any difference with `OPAQUE` fusion pattern.

My thought is that, for every ops, someone (likey the gpu driver) warps data layout transpose before and after to every op, since tensor core like NCHW.

However, I remembered that NHWC input for TVM is even slower than we do all the NCHW to NHWC transpose for tensor core, and we also need https://github.com/apache/incubator-tvm/pull/4456 for NHWC conv to work.

**Comment by anijain2305** [comment] 2019-12-31 00:10
@kice The ConvertLayout pass is merged now. I think you can give a try to convert the whole graph from NCHW to NHWC, if thats the current bottleneck for you. Currently, the conversion is supported only from NHWC -> NCHW. But, we can augment the pass to do the other way round as well.

**Comment by yzhliu** [comment] 2020-01-02 23:58
@kice could you confirm whether ConvertLayout helps to reduce the overhead?

**Comment by kice** [comment] 2020-01-18 12:37
ConvertLayout only support NHWC(tf) -> NCHW(tvm), but I used mxnet to make the layout conversion manually, and it turned out even slower. 

I think there is something to do with NVIDIA driver, I can still see layout conversion in nvprof.

**Comment by anijain2305** [comment] 2020-01-18 15:13
https://docs.tvm.ai/dev/convert_layout.html

Please use the above tutorial to add support for nchw to nhwc layout.

**Comment by tqchen** [comment] 2020-02-26 23:53
Close for now as depth2space is implemented. Please feel free to open new threads, or create discussions on the forum

**Closed** 2020-02-26 23:53 UTC
