### ISSUE TITLE
[BUG] topi.cuda.conv2d_winograd.winograd_cuda() not working when pre_computed=True

### ISSUE THREAD

**Issue by ghostplant** [apache/incubator-tvm#4514] opened 2019-12-12 12:50 UTC
`topi.cuda.conv2d_winograd.winograd_cuda()` get wrong `kernel_pack` shape and throw exceptions when `pre_computed=True`

**Comment by vinx13** [comment] 2019-12-12 21:00
can you provide a script to reproduce?

**Comment by ghostplant** [comment] 2019-12-13 05:28
```sh
    N, CI, H, W = 64, 3, 229, 229
    CO, KH, KW = 32, 3, 3
    stride, padding = 1, 1
    data = tvm.placeholder((N, CI, H, W), name='data')
    kernel = tvm.placeholder((CO, CI, KH, KW), name='kernel')
    cfg = autotvm.get_config()
    winograd_conv = topi.cuda.conv2d_winograd.winograd_cuda(cfg, data, kernel, (stride, stride), (padding, padding), dilation=1, layout='NCHW', out_dtype='float32', pre_computed=True)
    s = tvm.create_schedule([winograd_conv.op])
    topi.cuda.conv2d.schedule_winograd_cuda(cfg, s, winograd_conv.op.output(0), pre_computed=True)
```

**Comment by vinx13** [comment] 2019-12-13 05:31
`pre_computed` is not expected to be used in this way, it is called by Relay which run `AlterOpLayout` pass to change the layout. In your case, you should either set `pre_computed` should be False or use precomputed weight for the input

**Comment by ghostplant** [comment] 2019-12-13 05:36
@vinx13 I think earlier version doesn't have this issue.

**Comment by vinx13** [comment] 2019-12-13 05:38
Can you give a pointer which version?

**Comment by ghostplant** [comment] 2019-12-13 05:39
It is a status after v0.5 and before v0.6, but not able to find it easily now.

**Comment by masahi** [comment] 2019-12-13 06:45
@ghostplant even if a previous version didn't emit error, the result was likely not correct. If pre_computed = True, the kernel shape shouldn't be (CO, CI, KH, KW), so the error message is correct.

**Comment by masahi** [comment] 2019-12-13 06:47
Closing as it is not a bug

**Closed by masahi** 2019-12-13 06:47 UTC
